/** Nodi da gommone: nome, uso, passi e tracciati SVG (viewBox 0 0 260 320). */

export const KNOT_TERMS = [
  { term: "Corrente", def: "Il capo che muovi tu, quello che lavora." },
  { term: "Dormiente", def: "La parte di cima che sta ferma, verso il carico o la bitta." },
  { term: "Asola / occhio", def: "Un anello di cima. La gassa è un occhio che non deve scorrere." },
  { term: "Volta", def: "Un giro della cima intorno a un oggetto o a se stessa." },
]

export const KNOTS = [
  {
    id: "nodo-otto",
    name: "Nodo a otto",
    english: "Figure-eight",
    level: 1,
    why: "Fermo di sicurezza: la scotta non scappa dal bozzello o dalla mano.",
    onBoat: "In fondo alle scotte, alle cime di ormeggio corte, ovunque non vuoi perdere il capo.",
    warn: "",
    quizUse: "Quale nodo usi come fermo, perché la cima non sfili?",
    object: "none",
    steps: [
      {
        title: "Dormiente dritta",
        text: "Tieni la dormiente verticale. Il corrente è il capo libero in basso, arancio.",
        kind: "standing",
        d: "M 130 300 L 130 150",
        hit: { x: 130, y: 230 },
      },
      {
        title: "Prima volta",
        text: "Porta il corrente sopra la dormiente, verso destra, e inizia un giro largo.",
        kind: "working",
        d: "M 130 150 C 186 150 204 108 168 82",
        hit: { x: 186, y: 118 },
      },
      {
        title: "Incrocia dietro",
        text: "Il corrente passa dietro, incrocia, e forma il secondo occhio dell'otto.",
        kind: "working",
        d: "M 168 82 C 128 54 74 82 82 132 C 90 176 130 158 130 150",
        hit: { x: 86, y: 128 },
      },
      {
        title: "Dentro e stringi",
        text: "Infila il corrente nel primo occhio e tira. L'otto non deve scorrere.",
        kind: "working",
        d: "M 130 150 C 96 146 72 102 98 68 L 128 44",
        hit: { x: 108, y: 72 },
      },
    ],
  },
  {
    id: "nodo-piano",
    name: "Nodo piano",
    english: "Reef / square knot",
    level: 1,
    why: "Unisce due capi uguali in modo piatto. Va bene per un fagotto, non per un ormeggio.",
    onBoat: "Chiudere un telo, una rete, un pacco. Non per unire due cime di lavoro in mare.",
    warn: "Se i diametri sono diversi o tira a scatti, si capovolge. Per unire due cime usa il nodo bandiera.",
    quizUse: "Quale nodo è piatto e va bene per un telo, ma NON per unire due cime in mare?",
    object: "none",
    steps: [
      {
        title: "Due capi",
        text: "Due cime dello stesso diametro, una di fronte all'altra.",
        kind: "standing",
        d: "M 36 168 L 112 168 M 224 168 L 148 168",
        hit: { x: 70, y: 168 },
      },
      {
        title: "Destra sopra",
        text: "Destro sopra il sinistro, poi sotto: primo mezzo nodo.",
        kind: "working",
        d: "M 112 168 C 124 138 148 138 160 168 C 148 198 124 198 112 168",
        hit: { x: 136, y: 140 },
      },
      {
        title: "Sinistra sopra",
        text: "Ora il contrario: sinistro sopra il destro, poi sotto. Devono essere specchiati.",
        kind: "working",
        d: "M 112 168 C 124 198 148 198 160 168",
        hit: { x: 136, y: 196 },
      },
      {
        title: "Tira i quattro capi",
        text: "Se è piano vedi due anelli simmetrici. Se è storto (nodo granseola) disfa e rifai.",
        kind: "working",
        d: "M 112 168 L 78 118 M 160 168 L 194 118 M 112 168 L 78 218 M 160 168 L 194 218",
        hit: { x: 190, y: 168 },
      },
    ],
  },
  {
    id: "gassa-amante",
    name: "Gassa d'amante",
    english: "Bowline",
    level: 2,
    why: "L'anello che non stringe e si disfa anche dopo il carico. Il nodo del marinaio.",
    onBoat: "Ormeggio a un anello, cima su un parafango, asola di sicurezza, recupero.",
    warn: "Se resta scarica a lungo può allentarsi. In sicurezza si aggiunge un fermo o si fa la gassa doppia.",
    quizUse: "Quale nodo fa un anello che non scorre e si scioglie anche bagnato?",
    object: "none",
    steps: [
      {
        title: "Dormiente",
        text: "La dormiente è l'albero. Resta dritta. Il corrente è il coniglio.",
        kind: "standing",
        d: "M 156 300 L 156 132",
        hit: { x: 156, y: 230 },
      },
      {
        title: "La tana",
        text: "Col corrente fai un occhio sulla dormiente: la tana, con il verso che guarda il corrente.",
        kind: "working",
        d: "M 156 132 C 156 92 108 92 108 132 C 108 164 156 164 156 132",
        hit: { x: 108, y: 132 },
      },
      {
        title: "Il coniglio esce",
        text: "Il corrente sale da sotto e passa dentro la tana, verso di te.",
        kind: "working",
        d: "M 86 268 L 86 156 C 98 128 128 116 156 132",
        hit: { x: 86, y: 188 },
      },
      {
        title: "Gira l'albero",
        text: "Il coniglio gira dietro la dormiente (l'albero) e torna verso la tana.",
        kind: "working",
        d: "M 156 132 C 188 122 196 88 170 70 C 154 58 150 88 156 112",
        hit: { x: 184, y: 84 },
      },
      {
        title: "Rientra e stringi",
        text: "Di nuovo nella tana, giù. Tira dormiente e corrente: l'occhio grande non deve scorrere.",
        kind: "working",
        d: "M 156 112 C 136 128 114 146 92 168 L 78 214",
        hit: { x: 108, y: 158 },
      },
    ],
  },
  {
    id: "nodo-parlato",
    name: "Nodo parlato",
    english: "Clove hitch",
    level: 2,
    why: "Fissa una cima a un palo, una bitta, un candeliere. Veloce, regolabile.",
    onBoat: "Parabordi, palo dello scivolo, asta. Non è il nodo migliore se tira e slacca a raffiche.",
    warn: "Su un tubo liscio, se il tiro cambia senso, può girare. Completa con un mezzo collo se deve tenere.",
    quizUse: "Quale nodo metti in fretta intorno a un palo o a un parabordo?",
    object: "pole",
    steps: [
      {
        title: "Palo",
        text: "Il palo (o la bitta) sta fermo. Parti dal basso con il corrente.",
        kind: "standing",
        d: "M 64 300 L 64 200",
        hit: { x: 64, y: 250 },
      },
      {
        title: "Prima volta",
        text: "Giro completo intorno al palo, tornando dallo stesso lato da cui sei partito.",
        kind: "working",
        d: "M 64 200 C 64 168 196 168 196 200 C 196 232 64 232 64 200",
        hit: { x: 196, y: 200 },
      },
      {
        title: "Seconda volta",
        text: "Un secondo giro, più in alto, nello stesso senso. I due giri si incrociano a X sul davanti.",
        kind: "working",
        d: "M 64 200 C 64 136 196 136 196 108",
        hit: { x: 196, y: 136 },
      },
      {
        title: "Sotto l'incrocio",
        text: "Il corrente passa sotto la X e si tira. I due colli si bloccano a vicenda.",
        kind: "working",
        d: "M 196 108 C 196 78 86 78 78 118 L 72 156",
        hit: { x: 78, y: 118 },
      },
    ],
  },
  {
    id: "giro-morto",
    name: "Giro morto e due mezzi colli",
    english: "Round turn and two half hitches",
    level: 2,
    why: "Ormeggio classico a un anello: il giro morto prende il carico, i mezzi colli tengono.",
    onBoat: "Anello di banchina, gassa di un'altra cima, bitta bassa. Il nodo da ormeggio del gommone.",
    warn: "I mezzi colli vanno sulla dormiente, non sull'anello. Stringi sotto carico.",
    quizUse: "Quale nodo usi per ormeggiare a un anello, col carico sul giro e il fermo a colli?",
    object: "ring",
    steps: [
      {
        title: "Anello",
        text: "Passa il corrente nell'anello. La dormiente resta verso il gommone.",
        kind: "standing",
        d: "M 130 300 L 130 118",
        hit: { x: 130, y: 220 },
      },
      {
        title: "Giro morto",
        text: "Un giro e mezzo intorno all'anello: il metallo beve lo strappo, non il nodo.",
        kind: "working",
        d: "M 130 118 C 86 118 70 78 104 56 C 150 30 196 58 176 98 C 162 124 130 118 130 118",
        hit: { x: 78, y: 78 },
      },
      {
        title: "Primo mezzo collo",
        text: "Col corrente fai un mezzo collo intorno alla dormiente, sotto l'anello.",
        kind: "working",
        d: "M 176 98 C 200 130 168 168 130 168 C 108 168 108 196 130 196",
        hit: { x: 188, y: 140 },
      },
      {
        title: "Secondo mezzo collo",
        text: "Un secondo mezzo collo, stesso senso. Tira. Deve copiare il parlato sulla dormiente.",
        kind: "working",
        d: "M 130 196 C 162 196 168 230 130 236 C 98 242 92 268 118 278 L 148 286",
        hit: { x: 130, y: 236 },
      },
    ],
  },
  {
    id: "nodo-bandiera",
    name: "Nodo bandiera",
    english: "Sheet bend",
    level: 2,
    why: "Unisce due cime, anche di diametro diverso. Il nodo giusto al posto del nodo piano.",
    onBoat: "Allungare un ormeggio, unire una cima nuova a una vecchia, scotta su una randa di fortuna.",
    warn: "Il corrente della cima più sottile deve uscire dalla stessa parte della dormiente della più grossa.",
    quizUse: "Quale nodo usi per unire due cime, anche se una è più grossa?",
    object: "bight",
    steps: [
      {
        title: "Asola sulla grossa",
        text: "La cima più grossa (crema) fa solo un'asola. Non la nodare.",
        kind: "standing",
        d: "M 48 300 L 48 92",
        hit: { x: 48, y: 210 },
      },
      {
        title: "La sottile entra",
        text: "Il corrente della cima più sottile (arancio) entra nell'asola dal basso.",
        kind: "working",
        d: "M 210 300 L 210 150 C 200 118 150 108 118 118",
        hit: { x: 210, y: 210 },
      },
      {
        title: "Gira l'asola",
        text: "Gira dietro entrambi i capi dell'asola, un giro solo.",
        kind: "working",
        d: "M 118 118 C 78 128 58 88 92 68 C 128 46 168 68 168 108",
        hit: { x: 88, y: 72 },
      },
      {
        title: "Sotto se stessa",
        text: "Il corrente passa sotto di sé, dentro l'asola, e si tira. I due capi corti escono dallo stesso lato.",
        kind: "working",
        d: "M 168 108 C 168 138 138 148 118 132 L 118 118",
        hit: { x: 148, y: 140 },
      },
    ],
  },
]

export function getKnot(id) {
  return KNOTS.find((k) => k.id === id) || null
}
